config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :categories do
    resources :snippets, except: [:new, :create, :edit, :update, :destroy]
  end

  resources :snippets, only: [:new, :create, :edit, :update, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :snippets, dependent: :nullify
  validates :name, presence: true, uniqueness: true
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :category
  validates :title, presence: true, uniqueness: true
  validates :code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order("name ASC")
  end

  def new
    @category = Category.new
  end

  def create
    category_params = params.require(:category).permit(:name)
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Category created"
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category_params = params.require(:category).permit(:name)
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: "Category updated"
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category deleted"
    redirect_to categories_path
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def show
    @snippet = Snippet.find_by_category_id(params[:category_id])
  end

  def new
    @category = Category.all
    @snippet = Snippet.new
  end

  def create
    # render text: params
    snippet_params = params.require(:snippet).permit(:title, :code)
    @category = Category.find(params[:selected_category])
    @snippet = Snippet.new(snippet_params)
    @snippet.category = @category
    if @snippet.save
      redirect_to categories_path, notice: "Snippet created successfully"
    else
      @categories = Category.all
      render "snippets/new"
    end
  end

  def edit
    @category = Category.all
    @snippet = Snippet.find(params[:id])
  end

  def update
    snippet_params = params.require(:snippet).permit(:title, :code)
    @category = Category.find(params[:selected_category])
    @snippet = Snippet.find(params[:id])
    @snippet.category = @category
    if @snippet.update(snippet_params)
      redirect_to categories_path, notice: "Snippet updated"
    else
      render :edit
    end
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy
    redirect_to "#{categories_path}#snippets-for-#{@snippet.category.name.downcase}", aria: {expanded: true}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<% if @category.errors.any? %>
  <div class="alert alert-warning">
    <p>There were errors in your submissiontextile:</p>
    <p><%= @category.errors.full_messages.join(", ") %></p>
<% end %>
<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name, "Category Name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="panel panel-default">
      <%= f.button "<span class='glyphicon glyphicon-ok'></span>".html_safe, type: "submit", class: "btn btn-success padded" %>

      <span class="padded">Submit your new Category when you're ready.</span>
  </div>
<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

  <% @categories.each do |category| %>
    <div class="pull-right">
        <ul class="nav navbar-nav">
          <li><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe,
           edit_category_path(category), title: 'Edit Category' %></li>
        </ul>
        <div class="pull-right">
            <ul class="nav navbar-nav">
              <li><%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe,
                      category_path(category), method: :delete, data: {confirm: "Are you sure?"},
                      title: 'Delete Category' %></li>
            </ul>
        </div>
    </div>
    <div class="category-panel">
      <%=  link_to "#{category.name} <span class='badge'> #{category.snippets.count} <span class='glyphicon glyphicon-scissors'></span></span>".html_safe,
      "#snippets-for-#{category.name.downcase}",
      class: "snippet-link",
        data: { toggle: "collapse" } %>
    </div>
    <div class="snippet-group collapse" id='snippets-for-<%= "#{category.name.downcase}" %>'>
      <% category.snippets.each do |snippet| %>
        <div class="snippet-panel">
          <%= link_to "<span class='glyphicon glyphicon-scissors'></span> #{snippet.title}".html_safe, category_snippet_path(category, snippet) %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/categories/index.html.slim
h1 Snippets

/div class="category-panel"
/  h2 Ruby <span class="badge"> 5 <span class="glyphicon glyphicon-scissors"></span></span>

- @categories.each do |category|
  div class="category-panel"
    = link_to "#{category.name} <span class='badge'> #{category.snippets.count} <span class='glyphicon glyphicon-scissors'></span></span>".html_safe,
    "#snippets-for-#{category.name.downcase}",
    class: "snippet-link",
    data: { toggle: "collapse" }

  div class="snippet-group collapse" id="snippets-for-#{category.name.downcase}"
    - category.snippets.each do |snippet|
      div class="snippet-panel"
        = link_to "<span class='glyphicon glyphicon-scissors'></span> #{snippet.title}".html_safe, "snippet_path(snippet)"

app/views/categories/indextam.html.erb
<h2>Categories</h2>

  <% @categories.each do |category| %>
    <div class="pull-right">
        <ul class="nav navbar-nav">
          <li><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe,
           edit_category_path(category), title: 'Edit Category' %></li>
        </ul>
        <div class="pull-right">
            <ul class="nav navbar-nav">
              <li><%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe,
                      category_path(category), method: :delete, data: {confirm: "Are you sure?"},
                      title: 'Delete Category' %></li>
            </ul>
        </div>
    </div>
    <div class="category-panel">
      <%=  link_to "#{category.name} <span class='badge'> #{category.snippets.count} <span class='glyphicon glyphicon-scissors'></span></span>".html_safe,
      "#" + "snippets-for-#{category.name.downcase}".gsub(/[^0-9A-Za-z]/, ''),
      class: "snippet-link",
        data: { toggle: "collapse" } %>
    </div>
    <div class="snippet-group collapse" id='<%= "snippets-for-#{category.name.downcase}".gsub(/[^0-9A-Za-z]/, '') %>'>
      <% category.snippets.each do |snippet| %>
        <div class="snippet-panel">
          <%= link_to "<span class='glyphicon glyphicon-scissors'></span> #{snippet.title}".html_safe, category_snippet_path(category, snippet) %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/categories/new.html.erb
<h2>New Category</h2>

<% if @category.errors.any? %>
  <div class="alert alert-warning">
    <p>There were errors in your submissiontextile:</p>
    <p><%= @catgory.errors.full_messages.join(", ") %></p>
<% end %>
<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name, "Category Name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="panel panel-default">
      <%= f.button "<span class='glyphicon glyphicon-ok'></span>".html_safe, type: "submit", class: "btn btn-success padded" %>

      <span class="padded">Submit your new Category when you're ready.</span>
  </div>
<% end %>

app/views/categories/show.html.slim
h1 Categories#show
p Find me in app/views/categories/show.html.slim

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash-box notice">
    <p><%= flash[:notice] %></p>
  <div>
<% elsif flash[:alert] %>
  <div class="flash-box warning">
    <p><%= flash[:alert] %></p>
  </div>
<% end %>

app/views/layouts/_flash.html.slim
- if flash[:notice]
  div class="flash-box notice"
    p = flash[:notice]

- elsif flash[:alert]
  div class="flash-box warning"
    p = flash[:alert]

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">

    <div class="col-xs-10 col-sm-6">
      <div class="branding-icon" id="code-snippets-logo-collapse">
        <a class="navbar-brand"><span class="glyphicon glyphicon-scissors"></span></a>
      </div>
      <div class="navbar-header hidden-xs" id="code-snippets-logo-full">
          <%= link_to "Code Snippets", categories_path, class: "navbar-brand" %>
      </div>
      <div class="links_container">
        <ul class="nav navbar-nav">
          <li><%= link_to "New Category", new_category_path %></li>
        </ul>
      </div>
      <div class="links_container">
        <ul class="nav navbar-nav">
          <li><%= link_to "New Snippet", new_snippet_path %></li>
        </ul>
      </div>
  </div>
</div>
</nav>

<%# Since we're using fixed-top navbar, we need to push the content down a bit
 in order to properly clear everything %>
<div class="navbar-padding">
</div>

app/views/layouts/_navbar.html.slim
nav class="navbar navbar-default navbar-fixed-top"
  div class="container-fluid"

    div class="col-xs-10 col-sm-6"
      div class="branding-icon" id="code-snippets-logo-collapse"
        a class="navbar-brand" <span class="glyphicon glyphicon-scissors"></span>

      div class="navbar-header hidden-xs" id="code-snippets-logo-full"
        a class="navbar-brand" Code Snippets

      div class="links_container"
        ul class="nav navbar-nav"
          li = link_to "All Snippets", categories_path

    div class="col-xs-2 col-sm-6"
      div class="pull-right"
        ul class="nav navbar-nav"
         li = link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, "new_snippet_path", title: "New Snippet"
/ Alex: I'm changing here because we need to pass the catagory_id to create a new snippet (one-to-many)
/          li = link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, new_category_snippet_path(@categories), title: "New Snippet"

/ Since we're using fixed-top navbar, we need to push the content down a bit
/ in order to properly clear everything
div class="navbar-padding"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code Snippets</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render "/layouts/navbar" %>

      <%= render "/layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Code Snippets
    / highlight.js
    = stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/default.min.css'
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js'

    / asset pipeline
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    / CSRF
    = csrf_meta_tags

  body
    div class="container"
      = render "layouts/navbar"

      = render "layouts/flash"
      == yield

app/views/snippets/edit.html.erb
<h2>Edit Snippet</h2>

<% if @snippet.errors.any? %>
  <div class="alert alert-warning">
    <p>There were errors in your submissiontextile:</p>
    <p><%= @snippet.errors.full_messages.join(", ") %></p>
<% end %>
<%= form_for @snippet do |f| %>
  <div class="form-group">
    <%= label_tag "Select Category" %>
    <%= select_tag "selected_category", options_for_select(@category.collect {|c| [c.name, c.id]}), class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :title, "Snippet Name" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :code %>
    <%= f.text_area :code, class: "form-control" %>
  </div>
  <div class="panel panel-default">
      <%= f.button "<span class='glyphicon glyphicon-ok'></span>".html_safe, type: "submit", class: "btn btn-success padded" %>

      <span class="padded">Submit your code when you're ready.</span>
  </div>
<% end %>

app/views/snippets/index.html.slim
h1 Snippets
p Find me in app/views/snippets/index.html.slim

app/views/snippets/new.html.erb
<h2>New Snippet</h2>

<% if @snippet.errors.any? %>
  <div class="alert alert-warning">
    <p>There were errors in your submissiontextile:</p>
    <p><%= @snippet.errors.full_messages.join(", ") %></p>
<% end %>
<%= form_for @snippet do |f| %>
  <div class="form-group">
    <%= label_tag "Select Category" %>
    <%= select_tag "selected_category", options_for_select(@category.collect {|c| [c.name, c.id]}), class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :title, "Snippet Name" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :code %>
    <%= f.text_area :code, class: "form-control" %>
  </div>
  <div class="panel panel-default">
      <%= f.button "<span class='glyphicon glyphicon-ok'></span>".html_safe, type: "submit", class: "btn btn-success padded" %>

      <span class="padded">Submit your code when you're ready.</span>
  </div>
<% end %>

app/views/snippets/new.html.slim
h1 New Snippet

- if @snippet.errors.any?
  div class="alert alert-warning"
    p There were errors in your submissiontextile:
    p = @snippet.errors.full_messages.join(", ")

= form_for @snippet do |f|
  div class="form-group"
    = f.label :category
    = f.select :category, options_for_select(@categories.collect{|c| [c.name, c.name.downcase]}), {}, class: "form-control"

  div class="form-group"
    = f.label :title, "Snippet Name"
    = f.text_field :title, class: "form-control"

  div class="form-group"
    = f.label :code
    = f.text_area :code, class: "form-control"

  div class="panel panel-default"
      = f.button "<span class='glyphicon glyphicon-ok'></span>".html_safe, type: "submit", class: "btn btn-success padded"

      span class="padded" Submit your code when you're ready.

app/views/snippets/show.html.erb
<h2><%= @snippet.category.name %></h2>
<div>
<div class="panel panel-success">
    <div class="pull-right">
        <ul class="nav navbar-nav">
          <li><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_snippet_path(@snippet), title: 'Edit Snippet' %></li>
        </ul>
        <div class="pull-right">
            <ul class="nav navbar-nav">
              <li><%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, snippet_path(@snippet), method: :delete, data: {confirmation: "Are you sure?"}, title: 'Delete Snippet' %></li>
            </ul>
        </div>
    </div>
    <div class='panel-heading' style="padding: 15px 15px 15px"><%= @snippet.title %>
    </div>
  <div class="panel-body">
    <pre>
      <code class='<%= "#{@snippet.category.name.downcase}" %>'>
        <%= @snippet.code %>
      </code>
    </pre>
  </div>

</div>
<div>
  <%= link_to "back", categories_path, class: "btn btn-danger" %>
</div>

app/views/snippets/show.html.slim
h1 = @snippet.title
div class="panel panel-success"
  div class="panel-heading" = @snippet.category.name

  div class="panel-body"
    pre
      code class="#{@snippet.category.name.downcase}"
        = @snippet.code

div
  = link_to "back", categories_path, class: "btn btn-danger"